### ISSUE TITLE
Huge caching performance regression between 2.2.x and 2.3.x

### ISSUE THREAD

**Issue by jpreynat** [webpack-contrib/terser-webpack-plugin#221]
- Operating System: macOS Catalina
- Node Version: 10.15.3
- NPM Version: yarn 1.22.0
- webpack Version: 5.0.0-beta.13
- terser-webpack-plugin Version: 2.3.5

### Expected Behavior

Caching should not have degraded perfs with webpack 5.

### Actual Behavior

There seems to be a huge regression since v2.3.0 and using the webpack 5 filesystem cache.
Using the exact same config on our project and measuring the execution time of the `TaskRunner.run()` without any cache, here are the results:

```
terser-webpack-plugin@2.2.3
53355.023ms

terser-webpack-plugin@2.3.5
473181.662ms
```

You can see an increase of almost 10x, with no additional changes, and no existing cache, meaning that this is due only to the time spent trying to get in the cache or setting in the cache.

IMO, there's a big chance that the impact comes from the fact of writing directly to the filesystem for each operation might be the source of this increase.

A workaround could be to load the terser cache from filesystem into memory before running, using memory during the execution to ensure performant get/set for tasks, then flushing the updated cache to the filesystem once the plugin has finished running.

### Code

Here is our plugin config, which doesn't change before/after switching from `2.2.3` to `2.3.5`:

```js
minimizer: [
    new TerserPlugin({
        sourceMap: true,
        cache: path.join(CACHE_PATH, 'terser'),
        parallel: true,
        terserOptions: {
            safari10: true,
            mangle: true,
            compress: true,
            output: {
                comments: false
            }
        }
    })
],
```

### How Do We Reproduce?

Benchmark minifying a big project while switching from `terser-webpack-plugin@2.2.3` to `terser-webpack-plugin@2.3.5`.

**Comment by evilebottnawi** [comment]
I don't think we can solve this here, the cache API on webpack side. Can you create reproducible test repo with same structure and size? Don't forget terser that problem can be on terser side too. Can you try v2.3.2?

**Comment by jpreynat** [comment]
@evilebottnawi I didn't have the time to make a reproducible case using a testing repo.
However I tested using v2.3.2 and I've got the same order of magnitude than when using 2.3.5, the `TaskRunner` execution time being `398808.464ms`.

I was also running on the latest version of `terser` during both sets of tests.

**Comment by mems** [comment]
I've got a similar issue with a very large project.
The memory usage goes very high (v2.3.x take memory × 3 of v2.2.x) and node stop with this error :

```
Error: write UNKNOWN
←[90m    at ChildProcess.target._send (internal/child_process.js:813:20)←[39m
←[90m    at ChildProcess.target.send (internal/child_process.js:684:19)←[39m
    at ChildProcessWorker.send (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\workers\ChildProcessWorker.js:330:17)
    at WorkerPool.send (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\WorkerPool.js:32:34)
    at Farm._process (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\Farm.js:129:10)
    at Farm._enqueue (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\Farm.js:152:10)
    at Farm._push (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\Farm.js:159:12)
    at __REDACTED__\node_modules\←[4mjest-worker←[24m\build\Farm.js:90:14
    at new Promise (<anonymous>)
    at Farm.doWork (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\Farm.js:56:12)
    at JestWorker._callFunctionWithArgs (__REDACTED__\node_modules\←[4mjest-worker←[24m\build\index.js:178:23)
    at TaskRunner.runTask (__REDACTED__\node_modules\←[4mterser-webpack-plugin←[24m\dist\TaskRunner.js:41:26)
    at enqueue (__REDACTED__\node_modules\←[4mterser-webpack-plugin←[24m\dist\TaskRunner.js:89:35)
    at __REDACTED__\node_modules\←[4mterser-webpack-plugin←[24m\dist\TaskRunner.js:113:86
←[90m    at processTicksAndRejections (internal/process/task_queues.js:97:5)←[39m
Emitted 'error' event on ChildProcess instance at:
←[90m    at internal/child_process.js:817:39←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:79:11)←[39m {
  errno: ←[33m-4094←[39m,
  code: ←[32m'UNKNOWN'←[39m,
  syscall: ←[32m'write'←[39m
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I use Windows, Node.js v13.6.0 and webpack 5.0.0-beta.13

**Comment by evilebottnawi** [comment]
@jpreynat Sorry, without reproducible test repo hard to help, can you provide:
- Full configuration
- Number of entries (will be great to have number of modules, average)
- Size of input/output

Otherwise I can't help

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

I cannot investigate a performance problem without an example problem. Also, I do not see problems from other developers, no :+1: , no same problem, nothing.

Feel free to open a new issue with reproducible test repo.
