### ISSUE TITLE
2.3.3: Call retries were exceeded / ng build --prod / angular 9.0.4

### ISSUE THREAD

**Issue by andreialecu** [webpack-contrib/terser-webpack-plugin#223]
- Operating System: WSL Ubuntu
- Node Version: 13.7.0
- NPM Version: 6.13.6 (but using yarn 1.22.0)
- webpack Version: 4.41.2 (as per angular 9)
- terser-webpack-plugin Version: 2.3.3

### Expected Behavior

Shouldn't error out.

### Actual Behavior

```
yarn workspace proj-admin ng build --prod
yarn workspace v1.22.0
yarn run v1.22.0
$ /home/aandrei/projects/proj-monorepo/node_modules/.bin/ng build --prod

ERROR in 11-es2015.49a7d483ceac5d196479.js from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/aandrei/projects/proj-monorepo/packages/proj-admin/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:230:21)
    at ChildProcessWorker._onExit (/home/aandrei/projects/proj-monorepo/packages/proj-admin/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:307:12)
    at ChildProcess.emit (events.js:321:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/aandrei/.nvm/versions/node/v13.7.0/bin/node
Arguments: /usr/share/yarn/lib/cli.js ng build --prod
Directory: /home/aandrei/projects/proj-monorepo/packages/proj-admin
Output:
```

This is a vanilla angular 9.0.4 installation and I'm simply running `ng build --prod` on a fairly complex and big angular project.

I've noticed that a similar error was reported as fixed in 2.3.3, but as per `yarn.lock` I see that angular 9.0.4 uses the 2.3.3 version under the hood.

Any clues?

**Comment by andreialecu** [comment]
Apparently restarting and/or giving the WSL Ubuntu VM 10 GB of RAM made the error go away. It was assigned 6GB prior.

This seems pretty worrying as far as memory usage goes. The error might be caused by this:

https://github.com/webpack-contrib/terser-webpack-plugin/issues/202#issuecomment-589634287

Closing.
