### ISSUE TITLE
compilation.getCache is not a function

### ISSUE THREAD

**Issue by saravanan10393** [webpack-contrib/terser-webpack-plugin#290]
- Operating System: Mac 13+
- Node Version: 12+
- NPM Version: 6 +
- webpack Version: 5.0.0-beta.22
- terser-webpack-plugin Version: 3.1.0

### Expected Behavior
should compile smoothly

### Actual Behavior
Throwing following error
```js
HookWebpackError: compilation.getCache is not a function
    at makeWebpackError (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/lib/HookWebpackError.js:49:9)
    at /Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/webpack/lib/Compilation.js:1920:10
    at eval (eval at create (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- inner error --
TypeError: compilation.getCache is not a function
    at new Cache (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/terser-webpack-plugin/dist/Webpack5Cache.js:15:30)
    at TerserPlugin.optimizeFn (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/terser-webpack-plugin/dist/index.js:529:21)
    at _next0 (eval at create (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:17)
    at eval (eval at create (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:37:1)
    at /Users/Saravanan/projects/kf-xg-frontend/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:267:53
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
caused by plugins in Compilation.hooks.processAssets
TypeError: compilation.getCache is not a function
    at new Cache (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/terser-webpack-plugin/dist/Webpack5Cache.js:15:30)
    at TerserPlugin.optimizeFn (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/terser-webpack-plugin/dist/index.js:529:21)
    at _next0 (eval at create (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:17)
    at eval (eval at create (/Users/Saravanan/projects/kf-xg-frontend/base/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:37:1)
    at /Users/Saravanan/projects/kf-xg-frontend/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:267:53
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Code

```js
      new TerserPlugin({
        terserOptions: {
          ecma: 7,
          warnings: false,
          mangle: true, // Note `mangle.properties` is `false` by default.
          module: true,
          output: {
            comments: false
          },
          keep_classnames: true,
          keep_fnames: true
        },
        exclude: /^external.js$/,
        extractComments: true,
        sourceMap: shouldUseSourceMap,
        parallel: true
      }),
```

### How Do We Reproduce?

install `webpack@5.0.0-beta.22` and `terser-webpack-plugin@3.1.0` run the build.

**Comment by evilebottnawi** [comment]
It is mean you still do not use latest version of webpack https://github.com/webpack/webpack/tree/v5.0.0-beta.23

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v3.1.0

**Comment by saravanan10393** [comment]
Thank you @evilebottnawi.
