### ISSUE TITLE
Unhandled Error Event

### ISSUE THREAD

**Issue by lots0logs** [webpack-contrib/terser-webpack-plugin#307]
- Operating System: Ubuntu 20.04
- Node Version: 12.18.3
- NPM Version: N/A
- Yarn Version: 1.22.4
- webpack Version: 4.43.0
- terser-webpack-plugin Version: 2.3.8

### Expected Behavior

Finish without errors.

### Actual Behavior

```
throw er; // Unhandled 'error' event
^

Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at callback (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:32:17)
at module.exports (/core-products/Divi/includes/builder/frontend-builder/node_modules/terser-webpack-plugin/dist/worker.js:13:5)
at handle (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:44:8)
at process.<anonymous> (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:51:3)
at process.emit (events.js:315:20)
at emit (internal/child_process.js:876:12)
at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on process instance at:
at internal/child_process.js:810:39
at processTicksAndRejections (internal/process/task_queues.js:79:11) {
errno: 'EPIPE',
code: 'EPIPE',
syscall: 'write'
}
events.js:292
throw er; // Unhandled 'error' event
^

Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at callback (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:32:17)
at module.exports (/core-products/Divi/includes/builder/frontend-builder/node_modules/terser-webpack-plugin/dist/worker.js:13:5)
at handle (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:44:8)
at process.<anonymous> (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:51:3)
at process.emit (events.js:315:20)
at emit (internal/child_process.js:876:12)
at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on process instance at:
at internal/child_process.js:810:39
at processTicksAndRejections (internal/process/task_queues.js:79:11) {
errno: 'EPIPE',
code: 'EPIPE',
syscall: 'write'
}
events.js:292
throw er; // Unhandled 'error' event
^

Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at callback (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:32:17)
at module.exports (/core-products/Divi/includes/builder/frontend-builder/node_modules/terser-webpack-plugin/dist/worker.js:13:5)
at handle (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:44:8)
at process.<anonymous> (/core-products/Divi/includes/builder/frontend-builder/node_modules/worker-farm/lib/child/index.js:51:3)
at process.emit (events.js:315:20)
at emit (internal/child_process.js:876:12)
at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on process instance at:
at internal/child_process.js:810:39
at processTicksAndRejections (internal/process/task_queues.js:79:11) {
errno: 'EPIPE',
code: 'EPIPE',
syscall: 'write'
}
```

### Code
[webpack.config.js](https://gist.github.com/lots0logs/3f74a94ea2dc19688031cc66579d9d07)

### How Do We Reproduce?
Repo is private but will try to provide further information if needed.

**Comment by evilebottnawi** [comment]
Update plugin to latest version, `worker-farm` has bugs on new node.js version

**Comment by lots0logs** [comment]
The problem turned out to be the node process getting killed because of OOM inside the container. The memory limit was 2 GB. After setting a max of 4GB and a reservation of 1GB on the container the error no longer occurred.
