### ISSUE TITLE
`keep_classnames`  ValidationError: Terser Plugin Invalid Options

### ISSUE THREAD

**Issue by FishOrBear** [webpack-contrib/terser-webpack-plugin#32]
webpack 4.26.1
terser-webpack-plugin: 1.1.0

use config:
```
                new TerserPlugin({
                    cache: true,
                    parallel: true,
                    sourceMap: true,
                    keep_classnames: undefined,
                })
```

error log:

```
Terser Plugin Invalid Options

options should NOT have additional properties

ValidationError: Terser Plugin Invalid Options
    at validateOptions (\node_modules\terser-webpack-plugin\node_modules\schema-utils\src\validateOptions.js:32:11)
    at new TerserPlugin (\node_modules\terser-webpack-plugin\dist\index.js:48:31)
    at Object.<anonymous> (\config\webpack.prod.ts:14:17)
    at Module._compile (r\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Module.m._compile (\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
```

**Comment by edmorley** [comment]
Hi! Options related to `terser` (rather than `terser-webpack-plugin` which wraps `terser`), need to go under the `terserOptions` key rather than being placed at the top level.

See:
https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions

**Comment by FishOrBear** [comment]
Okay thank you
