### ISSUE TITLE
Unhandled Promise Rejection when using webpack 5 with storybook installed

### ISSUE THREAD

**Issue by daveisfera** [webpack-contrib/terser-webpack-plugin#322]
- Operating System: Debian Buster 10.5
- Node Version: 12.18.4
- NPM Version: yarn 1.22.4
- webpack Version: 5.0.0-rc.0
- terser-webpack-plugin Version: 4.2.2

### Expected Behavior
Package is bundled the same whether `storybook` is listed in `package.json` or not

### Actual Behavior
The generated code causes an unhandled exception when processing source maps:
```
(node:18) UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap.
    at BasicSourceMapConsumer.SourceMapConsumer_sourceContentFor [as sourceContentFor] (/usr/src/app/node_modules/source-map/lib/source-map-consumer.js:753:13)
    at /usr/src/app/web/node_modules/webpack-sources/lib/applySourceMap.js:144:46
    at SourceNode_walk [as walk] (/usr/src/app/node_modules/source-map/lib/source-node.js:230:9)
    at SourceNode_walk [as walk] (/usr/src/app/node_modules/source-map/lib/source-node.js:226:13)
    at applySourceMap (/usr/src/app/web/node_modules/webpack-sources/lib/applySourceMap.js:58:13)
    at SourceMapSource.node (/usr/src/app/web/node_modules/webpack-sources/lib/SourceMapSource.js:198:11)
    at exports.getSourceAndMap (/usr/src/app/web/node_modules/webpack-sources/lib/helpers.js:17:21)
    at SourceMapSource.sourceAndMap (/usr/src/app/web/node_modules/webpack-sources/lib/SourceMapSource.js:184:10)
    at getTaskForFile (/usr/src/app/web/node_modules/webpack/lib/SourceMapDevToolPlugin.js:77:30)
    at /usr/src/app/web/node_modules/webpack/lib/SourceMapDevToolPlugin.js:264:22
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Related to https://github.com/webpack/webpack/issues/11515

### Code
I don't currently have a minimal reproducer, but resolving the version of `terser` and `terser-webpack-plugin` fixed the problem

### How Do We Reproduce?
See previous comment

**Comment by evilebottnawi** [comment]
@daveisfera After investigate I can't reproduce (try with old/new version, with storybook) and I can't fix it, sorry, maybe something broken on `storybook`, please try to create reproducible test repo, otherwise I close issue, sorry

**Comment by evilebottnawi** [comment]
Reproduced, close in favor https://github.com/webpack/webpack-sources/issues/89

**Comment by blakmatrix** [comment]
I don't have storybook, I see the same issue, to get it to bundle the production code I had to change:

```js
  devtool: "source-map",
  optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        cache: true,
        sourceMap: true,
      }),]}
```

to

```js
  devtool: false,
  optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        cache: true,
        sourceMap: false,
      }),]}
```

This is with `webpack@5.0.0-rc.0` and `terser-webpack-plugin@4.2.2`

**Comment by evilebottnawi** [comment]
Bug found https://github.com/webpack/webpack-sources/issues/89
