### ISSUE TITLE
TypeError: Cannot read property 'javascript' of undefined

### ISSUE THREAD

**Issue by WangSuwen** [webpack-contrib/terser-webpack-plugin#339]
I got a problem：TypeError: Cannot read property 'javascript' of undefined , and i don`t know how to fix it...

**Comment by WangSuwen** [comment]
ERROR  TypeError: Cannot read property 'javascript' of undefined
TypeError: Cannot read property 'javascript' of undefined
    at compiler.hooks.compilation.tap.compilation (/Users/wxq/workspace//frontweb/node_modules/terser-webpack-plugin/dist/index.js:366:38)
    at SyncHook.eval [as call] (eval at create (/Users/wxq/workspace//frontweb/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at SyncHook.lazyCompileHook (/Users/wxq/workspace//frontweb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/wxq/workspace//frontweb/node_modules/webpack/lib/Compiler.js:631:26)
    at hooks.beforeCompile.callAsync.err (/Users/wxq/workspace//frontweb/node_modules/webpack/lib/Compiler.js:667:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/wxq/workspace//frontweb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/wxq/workspace/frontweb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/wxq/workspace/xx/frontweb/node_modules/webpack/lib/Compiler.js:662:28)
    at readRecords.err (/Users/wxq/workspace/xx/frontweb/node_modules/webpack/lib/Compiler.js:321:11)
    at Compiler.readRecords (/Users/wxq/workspace/xx/frontweb/node_modules/webpack/lib/Compiler.js:529:11)
    at hooks.run.callAsync.err (/Users/wxq/workspace/xx/frontweb/node_modules/webpack/lib/Compiler.js:318:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/wxq/workspace/xx/frontweb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/wxq/workspace/xx/frontweb/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/Users/wxq/workspace/xx/frontweb/node_modules/webpack/lib/Compiler.js:315:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/wxq/workspace/xx/frontweb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/wxq/workspace/xx/frontweb/node_modules/tapable/lib/Hook.js:154:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontweb@0.1.0 build: `vue-cli-service build --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontweb@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wxq/.npm/_logs/2020-10-19T06_39_53_019Z-debug.log

**Comment by evilebottnawi** [comment]
We don't support webpack@4, please use the issue template, respect time of other developers, thanks

**Comment by Etienereum** [comment]
Was having similar issue, because I was using some dependencies also in the devDependencies but with different versions in my package.json file.
