### ISSUE TITLE
yarn buld tips TypeError: Cannot read property 'javascript' of undefined

### ISSUE THREAD

**Issue by huyanhai** [webpack-contrib/terser-webpack-plugin#365]
(node:37720) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'javascript' of undefined
    at Proxy.<anonymous> (/Users/yhh/Documents/study/vue3_tools/node_modules/terser-webpack-plugin/dist/index.js:566:38)
    at /Users/yhh/Documents/study/vue3_tools/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:52:19
    at SyncHook.eval [as call] (eval at create (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:35:1)
    at SyncHook.lazyCompileHook (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at /Users/yhh/Documents/study/vue3_tools/node_modules/webpack/lib/CachePlugin.js:50:13
    at _next4 (eval at create (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/yhh/Documents/study/vue3_tools/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
(node:37720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
