### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by sibelius** [webpack-contrib/terser-webpack-plugin#376]
- Operating System: mac os x big sure 11.1
- Node Version: 14.15.4
- NPM Version: 6.14.10
- webpack Version: 5.3.1
- terser-webpack-plugin Version: 3.1.0
- serialize-javascript: 4.0.0

### Expected Behavior

it should not throw any error

### Actual Behavior

it throws this error

```jsx
RangeError: Invalid string length
at JSON.stringify (<anonymous>)
  at serialize (app/node_modules/serialize-javascript/index.js:184:20)
  at enqueue (app/node_modules/terser-webpack-plugin/dist/index.js:436:82)
  at app/node_modules/terser-webpack-plugin/dist/index.js:473:20
  at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Code

```js
{
  output: {
    path: 'build',
    library: 'index',
    libraryTarget: 'commonjs2',
    filename: 'app.js',
  },
  target: 'node',
  node: {
    __dirname: true,
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json', '.mjs'],
  },
  module: {
    rules: [
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      },
      {
        test: /\.(js|jsx|ts|tsx)?$/,
        use: {
          loader: 'babel-loader?cacheDirectory',
        },
        exclude: [/node_modules/],
      },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production'),
    }),
  ],
  mode: 'production',
  devtool: 'source-map',
  optimization: {
    minimizer: [new TerserPlugin({
      parallel: 4,
    })],
  },
  entry: {
    server: ['./src/index.ts'],
  },
};
```

### How Do We Reproduce?

just build using webpack

```jsx
webpack --progress --config webpack.prod.config.js
```

**Comment by alexander-akait** [comment]
What is version used? something wrong here in `serialize-javascript`, maybe you can create reportorial test repo

**Comment by sibelius** [comment]
upgraded to latest, and it is working

thanks
