### ISSUE TITLE
Terser TypeError: Cannot read property 'option' of undefined

### ISSUE THREAD

**Issue by ManoharChennuru** [webpack-contrib/terser-webpack-plugin#402]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**
   terser: v5.7.0

  "name": "terser-webpack-plugin",
  "version": "5.1.3",

I even tried with terser-webpack-plugin which comes out of the box with webpack v5.8.1

**`part of webpack config` **

```
optimization: {
        minimize: true,
        minimizer: [
            `...`,
            new CssMinimizerPlugin({
                exclude: /(node_modules)/,
            }),
        ],
    },
```

**`terser` output or error**

ERROR in main.6fbf132152a9d5a3a025.js from Terser
TypeError: Cannot read property 'option' of undefined
    at AST_Call.is_callee_pure (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:13763:20)
    at AST_Call.has_side_effects (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:13832:19)
    at is_undefined (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:12971:33)
    at D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:15552:12
    at AST_VarDef.optimize (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:10892:19)
    at Compressor.before (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:10877:24)
    at AST_VarDef.transform (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:5395:41)
    at D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:5411:21
    at doit (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:112:23)
    at MAP (D:\Users\xxx\Documents\Code\xxx\node_modules\terser\dist\bundle.min.js:137:52)

****Expected result**

Should see successful build**

**Comment by ManoharChennuru** [comment]
I have gone through the terser bundle file, which is clear that below code is causing the build failure.

def_optimize(AST_VarDef, function(self) {
    if (
        self.name instanceof AST_SymbolLet
        && self.value != null
        && is_undefined(self.value)
    ) {
        self.value = null;
    }
    return self;
});


If I update above def_optimise function like this

def_optimize(AST_VarDef, function(self, compressor) {
    if (
        self.name instanceof AST_SymbolLet
        && self.value != null
        && is_undefined(self.value, compressor)
    ) {
        self.value = null;
    }
    return self;
});
My issue is gone. Please advice how to proceed.

So question should configure Terser in any way other that just using `...` to by pass this error? or is it a bug?

**Comment by alexander-akait** [comment]
Please open an issue in terser repo https://github.com/terser/terser, sorry we can't fix it here, bug inside `terser`, feel free to feedback
