### ISSUE TITLE
DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)

### ISSUE THREAD

**Issue by allen-munsch** [webpack-contrib/terser-webpack-plugin#449]
### Actual Behavior

```
=> Found "terser-webpack-plugin@1.2.3"
=> Found "webpack#terser-webpack-plugin@5.2.4"
=> Found "webpack@5.52.0"
```

```
(node:123461) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
    at /home/jm/pycharm_projects/project/node_modules/terser-webpack-plugin/dist/index.js:347:45
    at _next43 (eval at create (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:42:1)
    at _next21 (eval at create (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:143:1)
    at Hook.CALL_DELEGATE [as _call] (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/jm/pycharm_projects/project/node_modules/webpack/lib/Compiler.js:1044:26)
    at /home/jm/pycharm_projects/project/node_modules/webpack/lib/Compiler.js:1088:29
    at Hook.eval [as callAsync] (eval at create (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/jm/pycharm_projects/project/node_modules/webpack/lib/Compiler.js:1083:28)
    at /home/jm/pycharm_projects/project/node_modules/webpack/lib/Compiler.js:508:12
    at Compiler.readRecords (/home/jm/pycharm_projects/project/node_modules/webpack/lib/Compiler.js:920:11)
    at /home/jm/pycharm_projects/project/node_modules/webpack/lib/Compiler.js:505:11
    at Hook.eval [as callAsync] (eval at create (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/jm/pycharm_projects/project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
```

### Expected Behavior

No warnings

### How Do We Reproduce?

use the above versions

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
11:24:35 jm@jm project ±|AA-726-jm-1 ✗|→ yarn webpack-cli info
yarn run v1.22.11
$ /home/jm/pycharm_projects/project/node_modules/.bin/webpack-cli info

  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 33.14 GB / 62.60 GB
  Binaries:
    Node: 14.16.1 - /tmp/yarn--1631204677580-0.45593572372467794/node
    Yarn: 1.22.11 - /tmp/yarn--1631204677580-0.45593572372467794/yarn
    npm: 6.14.12 - /home/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 91.0.2
  Packages:
    extract-css-chunks-webpack-plugin: ^4.9.0 => 4.9.0 
    fork-ts-checker-webpack-plugin: 6.1.0 => 6.1.0 
    image-webpack-loader: 4.6.0 => 4.6.0 
    karma-webpack: 3.0.5 => 3.0.5 
    optimize-css-assets-webpack-plugin: 5.0.1 => 5.0.1 
    terser-webpack-plugin: 1.2.3 => 1.2.3 
    tsconfig-paths-webpack-plugin: 3.2.0 => 3.2.0 
    webpack: ^5.52.0 => 5.52.0 
    webpack-bundle-analyzer: ^4.4.2 => 4.4.2 
    webpack-bundle-size-analyzer: ^3.1.0 => 3.1.0 
    webpack-cli: ^4.8.0 => 4.8.0 
```

**Comment by alexander-akait** [comment]
Remove `terser-webpack-plugin` from `package.json` or update it to the latest stable version

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/package.json#L3
