### ISSUE TITLE
Terser Plugin Invalid Options -- chunkFilter

### ISSUE THREAD

**Issue by jmtt89** [webpack-contrib/terser-webpack-plugin#45]
Documentation Is:
- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?
- [x] Not Working

### Please Explain in Detail...
This Example
```
module.exports = {
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        chunkFilter: (chunk) => {
          // Exclude uglification for the `vendor` chunk
          if (chunk.name === 'vendor') {
            return false;
          }
          return true;
        }
      }),
    ],
  },
};
```

produces this output
```
> webpack --config webpack.prod.js

Terser Plugin Invalid Options

options should NOT have additional properties

ValidationError: Terser Plugin Invalid Options
    at validateOptions (/Users/jtorres/Desktop/experiments/testProy/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new TerserPlugin (/Users/jtorres/Desktop/experiments/testProy/node_modules/terser-webpack-plugin/dist/index.js:48:31)
    at Object.<anonymous> (/Users/jtorres/Desktop/experiments/testProy/webpack.prod.js:10:7)
    at Module._compile (/Users/jtorres/Desktop/experiments/testProy/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (/Users/jtorres/Desktop/experiments/testProy/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test_proy@3.5.0 build: `webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test_proy@3.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jtorres/.npm/_logs/2018-12-20T22_06_12_647Z-debug.log
```

**Comment by evilebottnawi** [comment]
It is no published yes, release was today
