### ISSUE TITLE
Function with name `login` twice in the application breaks the build from terser

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [webpack-contrib/terser-webpack-plugin#461]
### Bug report
So, the bug sounds a it odd, but i was able to reproduce it again and again. When i have two functions with same name as `login`. The webpack build seems to breaks. And happens only when the `keep_fnames: true` option is turned on

### Actual Behavior

Builds the application without any error

### Expected Behavior

Builds the application without a js_error "login" redeclared error

### How Do We Reproduce?

- Create any webpack application, in my example i took react.
- Create a component and import it using `login` like `import login from 'login.tsx'`
- Enter into the `login` file and call a function which is under a object like `app.login()`
- Run `npm run build` the build breaks with an error.

### Error

```

ERROR in js/bundle.8f95fa6b2de4a0032758.min.js
js/bundle.8f95fa6b2de4a0032758.min.js from Terser plugin
"login" is redeclared [js/bundle.8f95fa6b2de4a0032758.min.js:112,35]
    at js_error (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:550:11)
    at TreeWalker.eval [as visit] (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:9661:17)
    at TreeWalker._visit (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:5136:24)
    at AST_SymbolConst._walk (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:3669:24)
    at AST_VarDef.eval (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:4369:23)
    at TreeWalker._visit (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:5140:21)
    at AST_VarDef._walk (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:4368:24)
    at AST_Const.eval (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:4339:32)
    at TreeWalker._visit (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:5140:21)
    at AST_Const._walk (/home/projects/github-b67fqc/node_modules/terser/dist/bundle.min.js:4336:24)
```

### Code Snippets

1. `app.tsx`

```jsx
const App = () => {
  return (
    <Router>
      <AppStateProvider>
        <Route exact component={login} path="/" />
      </AppStateProvider>
    </Router>
  );
};
```
2. `login.tsx`

```jsx
import app from './app';

const NamePage = () => {
  const loadUser = async () => {
    await app.login();
  };

  useEffect(() => {
    loadUser();
  }, []);
  return <div>Login Page</div>;
};

export default NamePage;
```

3. `app.tsx`

```jsx
const auth: Auth = {
  login: async () => {},
  logout: () => {},
};

export default auth;
```

### Now, coming for the weird behaviour part :!

- Here is the example that breaks
https://stackblitz.com/edit/github-b67fqc?file=src/login.tsx

- Here is the one that works with exact same pattern but the `login` is changed to `logout`
https://stackblitz.com/edit/github-b67fqc-eolwar?file=src/index.js

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  Packages:
    babel-loader: ^8.2.2 => 8.2.3 
    copy-webpack-plugin: ^9.0.1 => 9.1.0 
    css-loader: ^6.3.0 => 6.5.1 
    file-loader: ^6.2.0 => 6.2.0 
    html-webpack-plugin: ^5.3.2 => 5.5.0 
    postcss-loader: ^6.2.0 => 6.2.1 
    sass-loader: ^12.1.0 => 12.4.0 
    style-loader: ^3.3.0 => 3.3.1 
    terser-webpack-plugin: ^5.2.4 => 5.2.5 
    url-loader: ^4.1.1 => 4.1.1 
    webpack: ^5.59.1 => 5.65.0 
    webpack-cli: ^4.9.1 => 4.9.1 
    webpack-dev-server: ^4.3.1 => 4.6.0 
    webpack-merge: ^5.8.0 => 5.8.0
```

Please, feel free to close this if the issue is out of scope for the repo. But, i tried reproducing the same using `terser` cli. But, it is working fine, so thought it is something related to webpack build output itself 😅

**Comment by alexander-akait** [comment]
Please open an issue in `terser` repo, we just wrapper around `terser` tool

**Comment by alexander-akait** [comment]
https://github.com/terser/terser

**Comment by alexander-akait** [comment]
Here only one different in options, you can try to use terser cli with the same options

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1073

**Comment by alexander-akait** [comment]
Also you use `babel-loader`, to terser gets transpiled code, there is potential babel problem can be too

**Comment by JayaKrishnaNamburu** [comment]
Cool, i will try to reproduce using cli then 👍

**Comment by JayaKrishnaNamburu** [comment]
> Please open an issue in `terser` repo, we just wrapper around `terser` tool

Yup, just wanted to check if `webpack` is doing something here 😄

**Comment by alexander-akait** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

And feel free to feedback
