### ISSUE TITLE
sourceMapFilename ending with .js causes Unexpected token: punc (:) error

### ISSUE THREAD

**Issue by aovchinn** [webpack-contrib/terser-webpack-plugin#467]
### Bug report

if `webpack output.sourceMapFilename` (https://webpack.js.org/configuration/output/#outputsourcemapfilename)
ends with .js and devtool is `source-map`, production build fails with error

### Actual Behavior

webpack build fails with error
```
sourceMaps/index-entry.map.js from Terser plugin
Unexpected token: punc (:) [sourceMaps/index-entry.map.js:1,10]
    at js_error (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1288:9)
    at semicolon (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1326:56)
    at simple_statement (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1583:73)
    at statement (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1369:47)
    at _embed_tokens_wrapper (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1339:26)
    at block_ (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:2172:20)
    at statement (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1403:29)
```

### Expected Behavior

terser should not run on generated source maps, 
maybe output.sourceMapFilename could validate/warn that new name shouldn't end with .js

### How Do We Reproduce?

test repo: https://github.com/aovchinn/test-webpack-5-terser
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
PS C:\Users\petovchial\Desktop\test-webpack-5-terser> npx webpack-cli
assets by status 78 bytes [cached] 1 asset
./index.js 26 bytes [built] [code generated]

ERROR in sourceMaps/index-entry.map.js
sourceMaps/index-entry.map.js from Terser plugin
Unexpected token: punc (:) [sourceMaps/index-entry.map.js:1,10]
    at js_error (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1274:9)
    at token_error (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1288:9)
    at semicolon (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1326:56)
    at simple_statement (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1583:73)
    at statement (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1369:47)
    at _embed_tokens_wrapper (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1339:26)
    at block_ (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:2172:20)
    at statement (C:\Users\petovchial\Desktop\test-webpack-5-terser\node_modules\terser\dist\bundle.min.js:1403:29)

webpack 5.66.0 compiled with 1 error in 277 ms
```

**Comment by aovchinn** [comment]
workaround was simple, but it was hard to understand what was going wrong

fix is to use .map extension like 
`sourceMapFilename: "sourceMaps/[name].js.map"`
instead of
~`sourceMapFilename: "sourceMaps/[name].map.js"`~

**Comment by alexander-akait** [comment]
Because plugin try to parser source map as js file, you should not use `.js` at the end of source map file, because it is not js file, anyway if you need this you can use `exclude`

**Comment by aovchinn** [comment]
I encountered this during migration from v4 -> v5, so it was working before, somehow.

I also agree that source-maps should not have .js extension
maybe this ticket will help somebody in the same situation 😃
