### ISSUE TITLE
Need help!  TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by bigbigmyworld** [webpack-contrib/terser-webpack-plugin#495]
Operating System: Macos
webpack Version: 4.0.0
terser-webpack-plugin Version: 4.0.0
npm Version:6.13.4

Actual Behavior:
`@MacBook-Pro vendors % ykit pack -m
TypeError: Cannot read property 'compilation' of undefined
    at TerserPlugin.apply (/Users/tangyuanzheng/dev_code/yapi/vendors/node_modules/terser-webpack-plugin/dist/index.js:529:20)
    at Compiler.apply (/usr/local/lib/node_modules/ykit/node_modules/tapable/lib/Tapable.js:164:16)
    at WebpackOptionsApply.process (/usr/local/lib/node_modules/ykit/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/usr/local/lib/node_modules/ykit/node_modules/webpack/lib/webpack.js:22:48)
    at /usr/local/lib/node_modules/ykit/lib/commands/pack.js:236:13
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/ykit/node_modules/core-js/library/modules/_export.js:36:28)
    at Project.compilingProcess (/usr/local/lib/node_modules/ykit/lib/commands/pack.js:235:16)
    at Project._callee$ (/usr/local/lib/node_modules/ykit/lib/commands/pack.js:92:63)
    at tryCatch (/usr/local/lib/node_modules/ykit/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/ykit/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/ykit/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/ykit/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/ykit/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13`

Code:
`baseConfig.plugins.push(
            new TerserPlugin({
              terserOptions: {
                compress: {
                  warnings: false,
                },
                exclude: /node_modules/,
              },
            })
          );`

Code:
`ykit pack -m`

**Comment by alexander-akait** [comment]
Please open an issue in `ykit`
