### ISSUE TITLE
`nth_identifier` function that accesses global scope variable crashes

### ISSUE THREAD

**Issue by guilhermesimoes** [webpack-contrib/terser-webpack-plugin#554]
### Bug report

`nth_identifier` function that accesses global scope variable crashes. From going through terser-webpack-plugin's code it seems like this is due to the way the function we are trying to pass to Terser is serialized and passed to a worker.

### Actual Behavior

```
chars is not defined
ReferenceError: chars is not defined
    at Object.sort (eval at transform (~/project/node_modules/terser-webpack-plugin/dist/minify.js:43:3), <anonymous>:221:5)
    at Object.get (eval at transform (~/project/node_modules/terser-webpack-plugin/dist/minify.js:43:3), <anonymous>:268:12)
    at mangle (~/project/node_modules/terser/dist/bundle.min.js:29521:46)
    at TreeTransformer.before (~/project/node_modules/terser/dist/bundle.min.js:29462:33)
    at AST_Dot.transform (~/project/node_modules/terser/dist/bundle.min.js:6732:41)
    at ~/project/node_modules/terser/dist/bundle.min.js:6891:27
    at AST_Assign.transform (~/project/node_modules/terser/dist/bundle.min.js:6735:13)
    at ~/project/node_modules/terser/dist/bundle.min.js:6748:21
    at doit (~/project/node_modules/terser/dist/bundle.min.js:106:23)
    at MAP (~/project/node_modules/terser/dist/bundle.min.js:131:52)
```

### Expected Behavior

Variables should be mangled according to `nth_identifier`.

### How Do We Reproduce?

Use Terser's default `nth_identifier` function (which I'm trying to customise)
https://github.com/terser/terser/blob/6268e5fcbd0bad36603d5cd13d9b0da106c1a8dc/lib/scope.js#L1009-L1055
Copied here:
```ts
function mergeSort(array, cmp) {
  if (array.length < 2) {
    return array.slice();
  }
  function merge(a, b) {
    const r = [];
    let ai = 0;
    let bi = 0;
    let i = 0;
    while (ai < a.length && bi < b.length) {
      cmp(a[ai], b[bi]) <= 0 ? (r[i++] = a[ai++]) : (r[i++] = b[bi++]);
    }
    if (ai < a.length) {
      r.push.apply(r, a.slice(ai));
    }
    if (bi < b.length) {
      r.push.apply(r, b.slice(bi));
    }
    return r;
  }
  function _ms(a) {
    if (a.length <= 1) {
      return a;
    }
    const m = Math.floor(a.length / 2);
    let left = a.slice(0, m);
    let right = a.slice(m);
    left = _ms(left);
    right = _ms(right);
    return merge(left, right);
  }
  return _ms(array);
}

const leading = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$_'.split('');
const digits = '0123456789'.split('');
let chars;
let frequency;
function reset() {
  frequency = new Map();
  leading.forEach(function (ch) {
    frequency.set(ch, 0);
  });
  digits.forEach(function (ch) {
    frequency.set(ch, 0);
  });
}
function consider(str, delta) {
  for (let i = str.length; --i >= 0; ) {
    frequency.set(str[i], frequency.get(str[i]) + delta);
  }
}
function compare(a, b) {
  return frequency.get(b) - frequency.get(a);
}
function sort() {
  chars = mergeSort(leading, compare).concat(mergeSort(digits, compare));
}
// Ensure this is in a usable initial state.
reset();
sort();
function base54(num) {
  let ret = '';
  let base = 54;
  num++;
  do {
    num--;
    ret += chars[num % base];
    num = Math.floor(num / base);
    base = 64;
  } while (num > 0);
  return ret;
}

const nth_identifier = {
  consider,
  get: base54,
  reset,
  sort,
};
```
Webpack config:
```ts
minimizer: [
  new TerserPlugin({
    terserOptions: {
      ecma: 2018,
      mangle: {
        properties: {
          nth_identifier,
        },
      },
    },
  }),
],
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 785.75 MB / 32.00 GB
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.54
    Firefox: 110.0.1
    Safari: 16.1
  Packages:
    copy-webpack-plugin: 9.1.0 => 9.1.0 
    fork-ts-checker-webpack-plugin: 6.3.3 => 6.3.3 
    html-webpack-plugin: 5.3.2 => 5.3.2 
    terser-webpack-plugin: 5.3.6 => 5.3.6 
    webpack: 5.75.0 => 5.75.0 
    webpack-bundle-analyzer: 4.4.2 => 4.4.2 
    webpack-cli: 4.8.0 => 4.8.0 
    webpack-dev-server: 4.3.0 => 4.3.0 
    webpack-glsl-loader: 1.0.1 => 1.0.1 
    webpack-license-plugin: 4.2.2 => 4.2.2 
    webpack-retry-chunk-load-plugin: 2.2.0 => 2.2.0 
    webpack-stats-plugin: 1.0.3 => 1.0.3 
```

**Comment by alexander-akait** [comment]
Please open an issue in https://github.com/terser/terser repo, we are just a wrapper for minification tools, like terser/swc/esbuild/etc, thank you

**Comment by guilhermesimoes** [comment]
This is a terser-webpack-plugin bug, not terser's.

Like you can see in the crash log of my bug report, the crash occurs here:
https://github.com/webpack-contrib/terser-webpack-plugin/blob/11073e320e4e17634f2a04879c816ce6f3c9bc32/src/minify.js#L36-L43

**Comment by alexander-akait** [comment]
This is because you have:
```
function base54(num) {
  let ret = '';
  let base = 54;
  num++;
  do {
    num--;
    ret += chars[num % base];
    num = Math.floor(num / base);
    base = 64;
  } while (num > 0);
  return ret;
}
```

and `chars` is out of context, you need pre generate them and pass as an argument or rewrite function to do it in the scope (for example lazy), it is a limitation, sorry we can't fix it

**Comment by alexander-akait** [comment]
I.e.

```js
function base54(my_chars, num) {
  let ret = '';
  let base = 54;
  num++;
  do {
    num--;
    ret += my_chars[num % base];
    num = Math.floor(num / base);
    base = 64;
  } while (num > 0);
  return ret;
}

const bound_base54 = base54.bind(null, chars);

const nth_identifier = {
  consider,
  get: bound_base54,
  reset,
  sort,
};
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

**Comment by alexander-akait** [comment]
Feel free to feedback

**Comment by guilhermesimoes** [comment]
I know that `chars` is outside of the scope of that function. But that's fine. A function can access variables declared outside of its scope. It's how JavaScript works.
The example I gave, straight from Terser's own code, should work on terser-webpack-plugin because it is, like you said, "just a wrapper for minification tools".

I guess at the very least there should be a disclaimer in the README saying "hey, if your functions try to access variables declared outside of its scope it won't work because we're doing some parallel stuff with workers and we're stringifying all the functions you pass to us to then eval them inside the worker and that fails because we can't access those variables". Right? 🤔

**Comment by alexander-akait** [comment]
@guilhermesimoes Yeah makse sense to add this to docs, do you want to send a PR?

**Comment by Andreslav** [comment]
I managed to pass my nth_identifier! I had to package all the code into an object. I published the result here: https://gist.github.com/Andreslav/7f31d37b9f682e7b4f491f6b7de21900
