### ISSUE TITLE
since terser@3.16.0  i get TypeError: Cannot read property 'minify' of undefined

### ISSUE THREAD

**Issue by arpu** [webpack-contrib/terser-webpack-plugin#65]
looks like since today terser update i get 

ERROR in vendor.28ab9f9d78fdd25b0ab0.bundle.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/home/arpu/Work/projects/vrspace/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at module.exports (/home/arpu/Work/projects/vrspace/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (/home/arpu/Work/projects/vrspace/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/home/arpu/Work/projects/vrspace/node_modules/worker-farm/lib/child/index.js:51:3)
    at process.emit (events.js:197:13)
    at emit (internal/child_process.js:828:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

 yarn list | grep terser                                                                                                                                                                          1 ↵  11235  18:08:06 
├─ terser-webpack-plugin@1.2.1
│  ├─ terser@^3.8.1
├─ terser@3.16.0
│  ├─ terser-webpack-plugin@^1.1.0

**Comment by pitops** [comment]
@arpu It seems we opened the issue at the same time. Seem #66 for a possible workaround until its fixed (if you are using yarn)
