### ISSUE TITLE
Simplest webpack build crash

### ISSUE THREAD

**Issue by Xanngo** [webpack-contrib/terser-webpack-plugin#67]
* Operating System: Linux Mint 19
* Node Version: v10.5.0
* NPM Version: 6.1.0
* webpack Version: 4.29.0
* terser-webpack-plugin Version:terser-webpack-plugin@1.2.1

### Expected Behavior

Simplest webpack app should be able to build.

### Actual Behavior

Fails with error:

```
ERROR in main.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/home/chango/Proyectos/Chango/React/webpack-4-quickstart/node_modules/terser-webpack-plugin/dist/minify.js:176:23)
    at module.exports (/home/chango/Proyectos/Chango/React/webpack-4-quickstart/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (/home/chango/Proyectos/Chango/React/webpack-4-quickstart/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/home/chango/Proyectos/Chango/React/webpack-4-quickstart/node_modules/worker-farm/lib/child/index.js:51:3)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Code

```js
  // webpack.config.js
{
  "name": "webpack-4-quickstart",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1"
  }
}
```

### How Do We Reproduce?

On an empty folder run the following:

`$ npm init -y`
`$ npm i webpack --save-dev`
`$ npm i webpack-cli --save-dev`
`$ mkdir src && echo "console.log('Entry point');" > src/index.js`

Modify package.json:
```
"scripts": {
    "build": "webpack"
  },
```
`$ npm run build`

**Comment by csvan** [comment]
Fix has been implemented: https://github.com/terser-js/terser/pull/254

**Comment by bendg25** [comment]
Any ETA on this, the suggested workaround is not ideal and this is preventing me from doing a release.

**Comment by sgehrman** [comment]
just hit this too...

**Comment by edwardzhong** [comment]
my project also like this！

**Comment by csvan** [comment]
Several workarounds have already been mentioned, please follow the relevant links.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

**Comment by evilebottnawi** [comment]
Fixed in https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v1.2.2
